### ISSUE TITLE
The Visual Studio Code update prevented the Autolisp extension from working.

### ISSUE THREAD

**Issue by Junior-Nogueira** [Autodesk-AutoCAD/AutoLispExt#57] opened 2020-12-14 20:15 UTC
**Describe the bug**
My VsCode has been updated to the latest version and the extension is generating the error "couldn't find a debug adapter descriptor for debug type"

**To Reproduce**
Press on autolisp debug or RUN and the error happens
![Capturar](https://user-images.githubusercontent.com/60879372/102130675-e289d180-3e2f-11eb-89f3-633c3b9187a4.PNG)

**Comment by JD-Howard** [comment] 2020-12-14 20:59
I just uninstalled mine, re-installed the one from the marketplace, hit F5 and it worked fine.

What is interesting, my debug panel doesn't even show any configurations. So, I can only get to the Debug/Attach adapters through hitting F5. Please check that your AutoLispExt settings for launch paths are correct and try the F5 method that worked for me.

**Comment by JD-Howard** [comment] 2020-12-14 21:08
Correction, I just got a VSCode update that deprecated the debug adapter we were using. That adapter has been fixed in our code, but our new marketplace 1.4 has not gone live yet. For the time being, uninstall the AutoLispExt extension, download the automated extension build from the our [last RP](https://github.com/Autodesk-AutoCAD/AutoLispExt/releases/tag/v1.3.1-17e3b6da12e9d0180e7f4bd3da2387761dd5def7.0) and search the marketplace for a VSIX installer. This will give you our latest and greatest that does implement the new debug adapters.

**Comment by Junior-Nogueira** [comment] 2020-12-15 11:49
@JD-Howard When will version 1.4 be released?
I will try to install it using this method that you said I didn't know until then.

**Comment by JD-Howard** [comment] 2020-12-16 00:06
This doesn't prevent the extension from working, but I did just notice this automated VSIX is missing a file in this path:
_%username%\.vscode\extensions\autodesk.autolispext-1.3.1-17e3b6da12e9d0180e7f4bd3da2387761dd5def7.0\out\help_

This file operates the context menu "Open Online Help" feature. You can manually download this file from here:
_https://github.com/Autodesk-AutoCAD/AutoLispExt/blob/main/extension/src/help/webHelpAbstraction.json_

Again, doesn't break the app, but if you want that feature you'll have to put the file in the first path I provided. All of which assumes you got the VSIX installed by dumping it in a workspace and using the context menu to install it; possibly using an extension. I don't appear to have a VSIX installer extension and the option was there for me anyway.

**Comment by LanDong-adsk** [comment] 2020-12-16 00:41
We are working on a hotfix to fix the issue caused by VS code upgrade. 
As for 1.4.0, this is still under work and no concrete date for release yet.

**Comment by LanDong-adsk** [comment] 2020-12-18 01:57
1.3.2 is released to address this VScode update issue. Please try with the latest released build.

**Closed by LanDong-adsk** 2020-12-18 01:57 UTC
